# Generated by Django 3.1.3 on 2020-11-20 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='summary',
            field=models.CharField(default=1, max_length=450),
            preserve_default=False,
        ),
    ]
